apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  name: kafkachannel
  namespace: ns02
# disabled because of https://github.com/knative/eventing-contrib/issues/1659
#  annotations:
#    eventing.knative.dev/scope: namespace
spec:
  numPartitions: 10
  replicationFactor: 1
