apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: subscription
  namespace: ns04
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: InMemoryChannel
    name: imc
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sink
