apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: trigger
  namespace: ns05
spec:
  broker: broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sink
